service: samot-api
frameworkVersion: '2'
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  versionFunctions: false
  region: us-east-1
  runtime: nodejs12.x
  environment:
    ENV: ${opt:stage, 'prod'}
    MNEMONIC: ${ssm:mnemonic~true}
    INFURIA_KEY: ${ssm:infuria~true}
    NETWORK_URL: ${self:custom.NETWORK_URL.${self:provider.stage}}
    REVEAL: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "*"
      Resource: "*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  NETWORK_URL:
    dev: https://rinkeby.infura.io/v3/${self:provider.environment.INFURIA_KEY}
    prod: https://mainnet.infura.io/v3/${self:provider.environment.INFURIA_KEY}

functions:
  token:
    handler: handler.token
    events:
      - http:
          path: token/{collection}/{tokenId}
          method: get
          cors: true
  contract:
    handler: handler.contract
    events:
      - http:
          path: contract/{collection}
          method: get
          cors: true

resources:
  - ${file(./config/s3.yml)}




