service: samot-api
# frameworkVersion: '2'
provider:
  stage: ${opt:stage, 'dev'}
  name: aws
  versionFunctions: false
  region: us-east-1
  runtime: nodejs16.x
  environment:
    ENV: ${opt:stage, 'dev'}
    MNEMONIC: ${ssm:mnemonic}
    INFURIA_KEY: ${ssm:infuria}
    NETWORK_URL: ${self:custom.NETWORK_URL.${self:provider.stage}}
    REVEAL: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "*"
      Resource: "*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  NETWORK_URL:
    dev: https://rinkeby.infura.io/v3/${self:provider.environment.INFURIA_KEY}
    prod: https://mainnet.infura.io/v3/${self:provider.environment.INFURIA_KEY}

functions:
  samotclub:
    handler: handler.token
    environment:
      COLLECTION: samotclub
    events:
      - http:
          path: token/samotclub/{tokenId}
          method: get
          cors: true
  pyramyd:
    handler: handler.token
    environment:
      COLLECTION: pyramyd
    events:
      - http:
          path: token/pyramyd/{tokenId}
          method: get
          cors: true
  contract:
    handler: handler.contract
    events:
      - http:
          path: contract/{collection}
          method: get
          cors: true

resources:
  - ${file(./config/s3.yml)}




